name: 'Run Tests On Release'

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - release/**

jobs:
    backend-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0.x'
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build
            - name: Test with the dotnet CLI
              run: dotnet test

    frontend-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
